framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: selfhelp_app

        # Use Redis for persistent caching
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        # Namespaced cache pools for different categories
        pools:
            # Global cache pool for entities and API responses
            cache.global:
                adapter: cache.adapter.redis
                default_lifetime: 3600 # 1 hour default
                
            # Cache pool for user-specific frontend data
            cache.user_frontend:
                adapter: cache.adapter.redis
                default_lifetime: 1800 # 30 minutes for user-specific data
                
            # Cache pool for admin data
            cache.admin:
                adapter: cache.adapter.redis
                default_lifetime: 900 # 15 minutes for admin data
                
            # Cache pool for lookup data (longer TTL as it changes less)
            cache.lookups:
                adapter: cache.adapter.redis
                default_lifetime: 7200 # 2 hours for lookup data
                
            # Cache pool for permissions and ACL data
            cache.permissions:
                adapter: cache.adapter.redis
                default_lifetime: 1800 # 30 minutes for permissions
