nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%'] # Ensure this env var is 'http://127.0.0.1:3000' or 'http://localhost:3000'
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Client-Type'] # Added 'X-Client-Type'
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true  # <-- Add this line
    paths:
        '^/': null # This will inherit the defaults, including allow_credentials