ALTER TABLE `user_input` ADD `removed` BOOLEAN NOT NULL DEFAULT FALSE AFTER `edit_time`;

INSERT INTO `styles_fields` (`id_styles`, `id_fields`, `help`) VALUES ((select id from styles where `name` = 'showUserInput' limit 1), (select id from `fields` where `name` = 'label_delete' limit 1), 'The label of the remove button of the modal form.\n\nNote the following important points:\n- this field only has an effect if `is_log` is enabled.\n- if this field is not set, the remove button is not rendered.\n- entries that are removed with this button are only marked as removed but not deleted from the DB.');
INSERT INTO `styles_fields` (`id_styles`, `id_fields`, `help`) VALUES ((select id from styles where `name` = 'showUserInput' limit 1), (select id from `fields` where `name` = 'delete_title' limit 1), 'The title of the modal form that pops up when the delete button is clicked.\n\nNote the following important point:\n- this field only has an effect if `is_log` is enabled.');
INSERT INTO `styles_fields` (`id_styles`, `id_fields`, `help`) VALUES ((select id from styles where `name` = 'showUserInput' limit 1), (select id from `fields` where `name` = 'delete_content' limit 1), 'The content of the modal form that pops up when the delete button is clicked.\n\nNote the following important point:\n- this field only has an effect if `is_log` is enabled.');

UPDATE `styles_fields`, `styles`, `fields` SET `help` = 'The column title of the timestamp column.\n\nNote the following important point:\n- this field only has an effect if `is_log` is enabled.' WHERE `styles_fields`.`id_styles` = `styles`.`id` AND `styles`.`name` = 'showUserInput' AND `styles_fields`.`id_fields` = `fields`.`id` AND `fields`.`name` = 'label_date_time';
UPDATE `styles_fields`, `styles`, `fields` SET `help` = 'The name of the source form (i.e. the field `name` of the target form style).' WHERE `styles_fields`.`id_styles` = `styles`.`id` AND `styles`.`name` = 'showUserInput' AND `styles_fields`.`id_fields` = `fields`.`id` AND `fields`.`name` = 'source';
UPDATE `styles_fields`, `styles`, `fields` SET `help` = 'If *checked*, the style will render a table where each row represents all fields of the source form at the time instant of data submission.\n\nIf left *unchecked*, a table is rendered where each row represents one field of the source form.\n\nNote the following important points:\n- Check this only if the source form also has `is_log` checked.\n- The fields, `delete_title`, `label_date_time`, `label_delete`, and `delete_content` only have an effect if `is_log` is *checked*.' WHERE `styles_fields`.`id_styles` = `styles`.`id` AND `styles`.`name` = 'showUserInput' AND `styles_fields`.`id_fields` = `fields`.`id` AND `fields`.`name` = 'is_log';
